### ISSUE TITLE
How I Set Firewall to Low /Medium Or Paranoid???

### ISSUE THREAD

**Issue by crashangelbr** [jeremiedecock/iptables-scripts#1]
Hi, How I Set Firewall to Low /Medium Or Paranoid???

**Comment by jeremiedecock** [comment]
Install scripts [install-sysv.sh](https://github.com/jeremiedecock/iptables-scripts/blob/master/install-sysv.sh) and [install-upstart.sh](https://github.com/jeremiedecock/iptables-scripts/blob/master/install-upstart.sh) put firewall scripts in `/etc/`.

To *temporary* change the security level (i.e. until the next reboot), launch one of these scripts as root:
* `/etc/iptables-low.sh` to restrict incoming connections only (on IPv4 only)
* `/etc/iptables-medium.sh` to restrict incoming and outgoing connections (on IPv4 only)
* `/etc/iptables-paranoid.sh` to reject everything but loopback (on IPv4 and IPv6)
* `/etc/iptables-off.sh` to switch off the firewall (accept everything on IPv4 and IPv6)

The current policy can be checked with:
* `iptables -L -n -v` for IPv4
* `ip6tables -L -n -v` for IPv6.

Assuming you installed the firewall scripts with [install-sysv.sh](https://github.com/jeremiedecock/iptables-scripts/blob/master/install-sysv.sh) (as *upstart* is deprecated on recent Linux distributions), you can make this change permanent in [/etc/init.d/iptables-rules](https://github.com/jeremiedecock/iptables-scripts/blob/master/init-scripts/sysv/iptables-rules#L46) changing line 46 with the desired script.

For instance, to use the "medium" level at startup:

`IPTABLES_SCRIPT=/etc/iptables-medium.sh`
